export const localFeatureEnglish = {
    "modelParametersHint": "Choose per-session model presets",

    "changeProjectAvatar": "Change project avatar",
    "workingState": "Working",
    "attentionState": "Action needed",
    "onlineState": "Online",
    "offlineState": "Offline",

    "refreshConfiguration": "Refresh session configuration",
    "legacySessionConfig": "This running session predates safe configuration updates. Stop and resume it once to enable this feature. It will not be interrupted automatically.",
    "sessionConfigValidation": "Use positive whole token counts; the compaction threshold must be smaller than the context window.",
    "configQueued": "Queued; waiting for the session to become idle.",
    "configFailed": "Configuration update failed. The session was not replaced with a new conversation. Retry when connected.",
    "configRefreshing": "Loading the updated CLI for the same session…",
    "refreshWaiting": "Waiting to refresh",
    "refreshRestarting": "Restarting CLI and restoring session",
    "refreshVerifying": "Checking configuration and tools",
    "refreshComplete": "Refresh complete",
    "engineAuthRequired": "Authentication required",
    "engineAuthUnknown": "Authentication status unavailable",
    "engineAuthReady": "Authentication is configured",
    "engineAuthHint": "Run this command in a terminal on the session device, then check again:",
    "engineAuthCheck": "Check authentication",
    "engineAuthChecking": "Checking authentication…",
    "engineAuthCheckFailed": "Cannot check authentication. Check the device connection and try again.",
    "engineAgentUpgrade": "This Agent needs an update to support this action.",
    "refreshWaitHint": "Refresh starts after the current task and queued messages finish.",
    "refreshWaitTurn": "Waiting for the current turn to finish. Nothing is interrupted.",
    "refreshWaitPermission": "Waiting on the permission request above — answer it and the refresh continues.",
    "refreshSlow": "Taking longer than expected. Completion has not been confirmed; do not submit again.",
    "refreshStalled": "Refresh needs attention",
    "refreshStalledHint": "The CLI stopped, but restoration was not confirmed. Retry resumes this same session and keeps its history.",
    "refreshRetry": "Retry refresh",
    "refreshElapsed": "Elapsed",

    "dragSession": "Drag to reorder; arrow keys also move this session",
    "sessionMenu": "Session menu",
    "selected": "Selected",
    "speedHint": "Applies to newly started or restarted/resumed Codex sessions. Fast availability and usage depend on the model and account; Astra Fast uses 2.5× ChatGPT credits where available. API billing is separate.",

    "agents": "Agents",
    "agentsSubtitle": "Connected machines and agent defaults",
    "machines": "Machines",
    "noMachines": "No connected machines",
    "connectMachine": "Run LMC on a computer to connect it",
    "defaults": "Defaults",
    "clearOverrides": "Clear overrides",
    "clearDescription": "Return every agent to defaults",
    "permission": "Permission",
    "model": "Model",
    "effort": "Effort",
    "customModel": "Custom model…",
    "customCodex": "Custom Codex model",
    "modelId": "Enter an exact model ID",
    "modelHint": "Enter an exact model ID. Availability depends on your Codex account or API configuration.",
    "useDefault": "Use default",
    "defaultLabel": "Default",
    "none": "None",
    "contextHint": "Enter tokens; leave blank to use the backend default. Applies to newly started or restarted/resumed Codex sessions. Running sessions keep their existing configuration.",
    "windowHint": "For newly started or restarted sessions. Does not expand the model’s actual capacity.",
    "compactHint": "Codex may compact earlier according to its model limits.",
    "resetContext": "Use backend context defaults",
    "resetContextHint": "Clear both overrides for future starts and resumes",
    "positiveTokens": "Enter a positive whole number of tokens, or leave blank for the backend default.",
    "compactBelowWindow": "Auto-compaction threshold must be smaller than the context window.",
    "renameSession": "Rename session",
    "renameHint": "This name is synced with your account and will not be replaced by automatic CLI titles.",
    "namePlaceholder": "Session name",
    "invalidName": "Enter a name of 1–200 characters.",
    "resetName": "Restore automatic name",
    "archive": "Archive",
    "session": "Session",
    "clientLogs": "Client logs",
    "auto": "Auto",
    "workspace": "Workspace",
    "readOnly": "Read",
    "yolo": "Yolo",
    "edits": "Edits",
    "plan": "Plan",
    "customModelDescription": "custom model",
    "millionContext": "1M context",
    "invalidEffort": "Model and reasoning effort are incompatible. Message not sent. Choose a supported level: ",
    "project": "Project",
    "worktree": "Worktree",
    "searchMachine": "Search machines…",
    "searchWorkspace": "Search workspaces…",
    "searchWorktree": "Search worktrees…",
    "searchAgent": "Search agents…",
    "searchModel": "Search models…",
    "searchEffort": "Search efforts…",
    "searchPermission": "Search permissions…",
    "newWorktree": "New worktree",
    "noWorktree": "No worktree",
    "createNew": "Create new",
    "mainWorkspace": "Main"
};

export const localFeatureZhHans = {
    "modelParametersHint": "选择本会话的模型参数预设",

    "changeProjectAvatar": "更换头像",
    "workingState": "工作中",
    "attentionState": "待确认",
    "onlineState": "在线",
    "offlineState": "离线",

    "refreshConfiguration": "刷新会话配置",
    "legacySessionConfig": "这个运行中的会话尚未支持安全更新。请先停止并恢复一次，即可使用此功能；系统不会自动打断它。",
    "sessionConfigValidation": "请输入正整数 token 数；压缩阈值必须小于上下文窗口。",
    "configQueued": "已排队，等待会话空闲后应用。",
    "configFailed": "配置更新失败，未创建替代会话。请在连接正常后重试。",
    "configRefreshing": "正在为原会话加载更新后的 CLI…",
    "refreshWaiting": "等待刷新",
    "refreshRestarting": "正在重启 CLI、恢复原会话",
    "refreshVerifying": "正在检查配置与工具",
    "refreshComplete": "刷新完成",
    "engineAuthRequired": "需要登录认证",
    "engineAuthUnknown": "暂时无法确认认证状态",
    "engineAuthReady": "已检测到登录配置",
    "engineAuthHint": "请在本会话所在设备的终端执行下方命令，登录后重新检查：",
    "engineAuthCheck": "重新检查认证",
    "engineAuthChecking": "正在检查认证…",
    "engineAuthCheckFailed": "认证检查失败，请检查设备连接后重试。",
    "engineAgentUpgrade": "当前 Agent 版本不支持此操作，请更新后恢复会话。",
    "refreshWaitHint": "当前任务与排队消息结束后自动刷新。",
    "refreshWaitTurn": "等当前回合跑完，不会打断它。",
    "refreshWaitPermission": "在等上面那条权限请求——你回复了就继续。",
    "refreshSlow": "耗时较长，尚未确认完成，请勿重复提交。",
    "refreshStalled": "刷新需要处理",
    "refreshStalledHint": "CLI 已停止，但未确认恢复成功。重试会恢复当前会话，并保留历史记录。",
    "refreshRetry": "重试刷新",
    "refreshElapsed": "已等待",

    "dragSession": "拖动排序，也可用上下方向键移动会话",
    "sessionMenu": "会话菜单",
    "selected": "已选择",
    "speedHint": "对新建或重新启动／恢复的 Codex 会话生效。快速模式的可用性与额度消耗取决于模型和账号；Astra Fast 可用时消耗 2.5 倍 ChatGPT 额度，API 单独计费。",

    "agents": "智能体",
    "agentsSubtitle": "已连接的设备与智能体默认设置",
    "machines": "设备",
    "noMachines": "暂无已连接的设备",
    "connectMachine": "在电脑上运行 LMC 即可连接",
    "defaults": "默认设置",
    "clearOverrides": "清除自定义设置",
    "clearDescription": "恢复所有智能体的默认设置",
    "permission": "权限模式",
    "model": "模型",
    "effort": "推理强度",
    "customModel": "自定义模型…",
    "customCodex": "自定义 Codex 模型",
    "modelId": "输入完整模型 ID",
    "modelHint": "输入完整模型 ID。是否可用取决于 Codex 账号或 API 配置。",
    "useDefault": "使用默认设置",
    "defaultLabel": "默认",
    "none": "无",
    "contextHint": "输入 token 数，留空使用后端默认值。仅对新建或重新启动恢复的 Codex 会话生效，正在运行的会话保持原配置。",
    "windowHint": "对新建或重新启动的会话生效，不会扩大模型的实际容量。",
    "compactHint": "Codex 可能根据模型限制提前压缩。",
    "resetContext": "恢复后端上下文默认设置",
    "resetContextHint": "清除两项自定义值，下次启动或恢复时使用后端默认设置",
    "positiveTokens": "请输入正整数 token 数，或留空使用后端默认值。",
    "compactBelowWindow": "自动压缩阈值必须小于上下文窗口大小。",
    "renameSession": "重命名会话",
    "renameHint": "名称随账号同步，CLI 自动生成的标题不会覆盖它。",
    "namePlaceholder": "会话名称",
    "invalidName": "请输入 1～200 个字符的会话名称。",
    "resetName": "恢复自动命名",
    "archive": "归档",
    "session": "会话",
    "clientLogs": "客户端日志",
    "auto": "自动",
    "workspace": "工作区",
    "readOnly": "只读",
    "yolo": "完全放行",
    "edits": "允许编辑",
    "plan": "规划",
    "customModelDescription": "自定义模型",
    "millionContext": "1M 上下文",
    "invalidEffort": "模型与推理强度不兼容，消息未发送。请选择支持的强度：",
    "project": "项目",
    "worktree": "工作树",
    "searchMachine": "搜索设备…",
    "searchWorkspace": "搜索工作区…",
    "searchWorktree": "搜索工作树…",
    "searchAgent": "搜索智能体…",
    "searchModel": "搜索模型…",
    "searchEffort": "搜索推理强度…",
    "searchPermission": "搜索权限模式…",
    "newWorktree": "新建工作树",
    "noWorktree": "不使用工作树",
    "createNew": "新建",
    "mainWorkspace": "主工作区"
};

export const localFeatureZhHant = {
    "modelParametersHint": "選擇本工作階段的模型參數預設",

    "changeProjectAvatar": "更換頭像",
    "workingState": "工作中",
    "attentionState": "待確認",
    "onlineState": "線上",
    "offlineState": "離線",

    "refreshConfiguration": "重新載入工作階段設定",
    "legacySessionConfig": "這個執行中的工作階段尚未支援安全更新。請先停止並恢復一次，即可使用此功能；系統不會自動打斷它。",
    "sessionConfigValidation": "請輸入正整數 token 數；壓縮閾值必須小於上下文視窗。",
    "configQueued": "已排隊，等待工作階段閒置後套用。",
    "configFailed": "設定更新失敗，未建立替代工作階段。請在連線正常後重試。",
    "configRefreshing": "正在為原工作階段載入更新後的 CLI…",
    "refreshWaiting": "等待重新整理",
    "refreshRestarting": "正在重新啟動 CLI、恢復原工作階段",
    "refreshVerifying": "正在檢查設定與工具",
    "refreshComplete": "重新整理完成",
    "engineAuthRequired": "需要登入驗證",
    "engineAuthUnknown": "暫時無法確認驗證狀態",
    "engineAuthReady": "已偵測到登入設定",
    "engineAuthHint": "請在本對話所在裝置的終端執行下方命令，登入後重新檢查：",
    "engineAuthCheck": "重新檢查驗證",
    "engineAuthChecking": "正在檢查驗證…",
    "engineAuthCheckFailed": "驗證檢查失敗，請檢查裝置連線後重試。",
    "engineAgentUpgrade": "目前 Agent 版本不支援此操作，請更新後恢復對話。",
    "refreshWaitHint": "目前任務與排隊訊息結束後自動重新整理。",
    "refreshWaitTurn": "等目前回合跑完，不會打斷它。",
    "refreshWaitPermission": "在等上面那條權限請求——你回覆了就繼續。",
    "refreshSlow": "耗時較長，尚未確認完成，請勿重複提交。",
    "refreshStalled": "重新整理需要處理",
    "refreshStalledHint": "CLI 已停止，但尚未確認恢復成功。重試會恢復目前會話，並保留歷史記錄。",
    "refreshRetry": "重試重新整理",
    "refreshElapsed": "已等待",

    "dragSession": "拖動排序，也可用上下方向鍵移動工作階段",
    "sessionMenu": "工作階段選單",
    "selected": "已選擇",
    "speedHint": "對新建或重新啟動／恢復的 Codex 工作階段生效。快速模式的可用性與額度消耗取決於模型和帳號；Astra Fast 可用時消耗 2.5 倍 ChatGPT 額度，API 單獨計費。",

    "agents": "智慧代理",
    "agentsSubtitle": "已連線的裝置與智慧代理預設設定",
    "machines": "裝置",
    "noMachines": "暫無已連線的裝置",
    "connectMachine": "在電腦上執行 LMC 即可連線",
    "defaults": "預設設定",
    "clearOverrides": "清除自訂設定",
    "clearDescription": "還原所有智慧代理的預設設定",
    "permission": "權限模式",
    "model": "模型",
    "effort": "推理強度",
    "customModel": "自訂模型…",
    "customCodex": "自訂 Codex 模型",
    "modelId": "輸入完整模型 ID",
    "modelHint": "輸入完整模型 ID。是否可用取決於 Codex 帳號或 API 設定。",
    "useDefault": "使用預設設定",
    "defaultLabel": "預設",
    "none": "無",
    "contextHint": "輸入 token 數，留空使用後端預設值。僅對新建或重新啟動恢復的 Codex 對話生效，執行中的對話維持原設定。",
    "windowHint": "對新建或重新啟動的對話生效，不會擴大模型的實際容量。",
    "compactHint": "Codex 可能依模型限制提前壓縮。",
    "resetContext": "還原後端上下文預設設定",
    "resetContextHint": "清除兩項自訂值，下次啟動或恢復時使用後端預設設定",
    "positiveTokens": "請輸入正整數 token 數，或留空使用後端預設值。",
    "compactBelowWindow": "自動壓縮門檻必須小於上下文視窗大小。",
    "renameSession": "重新命名對話",
    "renameHint": "名稱隨帳號同步，CLI 自動產生的標題不會覆蓋它。",
    "namePlaceholder": "對話名稱",
    "invalidName": "請輸入 1～200 個字元的對話名稱。",
    "resetName": "還原自動命名",
    "archive": "封存",
    "session": "對話",
    "clientLogs": "用戶端記錄",
    "auto": "自動",
    "workspace": "工作區",
    "readOnly": "唯讀",
    "yolo": "完全放行",
    "edits": "允許編輯",
    "plan": "規劃",
    "customModelDescription": "自訂模型",
    "millionContext": "1M 上下文",
    "invalidEffort": "模型與推理強度不相容，訊息未傳送。請選擇支援的強度：",
    "project": "專案",
    "worktree": "工作樹",
    "searchMachine": "搜尋裝置…",
    "searchWorkspace": "搜尋工作區…",
    "searchWorktree": "搜尋工作樹…",
    "searchAgent": "搜尋智慧代理…",
    "searchModel": "搜尋模型…",
    "searchEffort": "搜尋推理強度…",
    "searchPermission": "搜尋權限模式…",
    "newWorktree": "新增工作樹",
    "noWorktree": "不使用工作樹",
    "createNew": "新增",
    "mainWorkspace": "主工作區"
};
