export const localFeatureEnglish = {
    "quotaTitle": "Account usage",
    "quotaRefresh": "Refresh usage",
    "quotaUnknown": "No data",
    "quotaPending": "Starts on first use",
    "quotaAwaitReset": "Awaiting a fresh window",
    "quotaFiveHour": "5-hour remaining",
    "quotaWeekly": "Weekly remaining",
    "quotaFable": "Fable weekly remaining",
    "quotaFableSpent": "Fable used up this week",
    "quotaFableCovered": "Covered by weekly quota",
    "quotaFableConvention": "Dashboard convention: full Fable pool = 50 weekly points",
    "quotaWaiting": "Waiting for a quota sample",
    "quotaStale": "Last known reading",
    "quotaOffline": "Waiting for a configured quota device to connect",
    "quotaRetryHint": "Unable to refresh. Retrying automatically.",
    "quotaShared": "Same account shared across devices · no summing",
    "quotaPaceMarker": ({ floor }: { floor: string }) => `Daily allowance floor: ${floor}%`,
    "quotaReset": ({ date }: { date: string }) => `Resets ${date}`,
    "quotaPaceDay": ({ day, days }: { day: number; days: number }) => `Day ${day}/${days} · daily split`,
    "quotaOver": ({ points }: { points: string }) => `${points} points over today's budget`,
    "quotaToday": ({ points }: { points: string }) => `${points} points left today`,
    "quotaFableShare": ({ points }: { points: string }) => `≈ ${points} weekly pts`,
    "quotaFableGap": ({ points }: { points: string }) => `${points} pts short`,
    "quotaFableSyncPending": "Awaiting matching reset",
    "quotaCredits": ({ count }: { count: number }) => `${count} quota reset credits`,
    "quotaExpires": ({ date }: { date: string }) => `Earliest expiry ${date}`,
    "quotaSampled": ({ date }: { date: string }) => `Sampled ${date}`,

    "loginContinue": "Continue sign-in",
    "loginViewRecovery": "View recovery",
    "loginTitle": "Sign in again",
    "loginHint": "Authorize on this device to reconnect the session device. Your draft, history and queue stay in place.",
    "loginRecheck": "Already signed in? Check again",
    "loginAutoCheck": "Checking authentication and attempting safe recovery…",
    "loginOpen": "Open official authorization",
    "loginOfficialHint": "Finish signing in on the official page. If it provides a one-time authorization code, return here to paste it.",
    "loginGoogleHint": "On the official page, choose Continue with Google if that is how you sign in.",
    "loginDeviceHint": "Enter the device code on the official page. This device will detect authorization automatically.",
    "loginCopyLink": "Copy authorization link",
    "loginCopied": "Copied",
    "loginHasCode": "I have an authorization code",
    "loginCodeTitle": "Paste the authorization code",
    "loginCodeHint": "Use the one-time code from the official page. It is sent encrypted to the target device and is never saved in chat.",
    "loginCodePlaceholder": "One-time authorization code",
    "loginSubmit": "Submit and verify",
    "loginBack": "Back to authorization",
    "loginWaiting": "Waiting for authorization",
    "loginStarting": "Starting login on the target device…",
    "loginSubmitting": "Submitting the code…",
    "loginVerifying": "Checking target device authentication…",
    "loginRecovering": "Sign-in detected · recovering sessions",
    "loginComplete": "Session recovery results",
    "loginRestored": "Restored",
    "loginWaitTurn": "Waiting for a safe turn boundary",
    "loginFailedSession": "Recovery needs attention",
    "loginSafeHint": "Busy sessions finish their current turn and queued input before refreshing. Closing this panel does not interrupt recovery.",
    "loginNoResend": "Tasks are never resent automatically. Check the original turn before deciding whether to send it again.",
    "loginKeepRunning": "You can close this panel and continue on another signed-in device.",
    "loginLifetime": "LMC login attempt remaining",
    "loginClose": "Close",
    "loginReturn": "Return to session",
    "loginCancel": "Cancel this login",
    "loginRetry": "Start a new login",
    "loginRetryRecovery": "Check and retry recovery",
    "loginQr": "Scan with your phone to authorize",
    "loginDevice": "Target device",
    "loginErrorRequired": "No sign-in was found. Sign in again to continue.",
    "loginErrorUnknown": "Authentication could not be verified. This does not mean you are signed out. Check the connection and retry.",
    "loginErrorUnsupported": "This session uses a custom authentication configuration. Use its original login method on the target device.",
    "loginErrorOffline": "The target device or session is unavailable. Reconnect it, then check again.",
    "loginErrorUpgrade": "Update both the device Agent and this session to use remote sign-in. The current session will not be interrupted.",
    "loginErrorBusy": "A login or recovery is already in progress. Continue that attempt.",
    "loginErrorInvalidCode": "The code could not be accepted. Check it, or start a new login.",
    "loginErrorLoginFailed": "The official login did not complete. Start a new login; for device login, check that your account allows it.",
    "loginErrorStale": "This login attempt is no longer active. Check for a newer attempt.",
    "loginErrorCancelled": "Login cancelled. Your sessions and messages were kept.",
    "loginErrorExpired": "This LMC login attempt timed out. Start a new login.",
    "modelParametersHint": "Choose per-session model presets",

    "changeProjectAvatar": "Change project avatar",
    "workingState": "Working",
    "attentionState": "Action needed",
    "onlineState": "Online",
    "offlineState": "Offline",

    "refreshConfiguration": "Refresh session configuration",
    "legacySessionConfig": "This running session predates safe configuration updates. Stop and resume it once to enable this feature. It will not be interrupted automatically.",
    "sessionConfigValidation": "Use positive whole token counts; the compaction threshold must be smaller than the context window.",
    "configQueued": "Queued; waiting for the session to become idle.",
    "configFailed": "Configuration update failed. The session was not replaced with a new conversation. Retry when connected.",
    "configRefreshing": "Loading the updated CLI for the same session…",
    "refreshWaiting": "Waiting to refresh",
    "refreshRestarting": "Restarting CLI and restoring session",
    "refreshVerifying": "Checking configuration and tools",
    "refreshComplete": "Refresh complete",
    "engineAuthRequired": "Authentication required",
    "engineAuthUnknown": "Authentication status unavailable",
    "engineAuthReady": "Authentication is configured",
    "engineAuthHint": "Run this command in a terminal on the session device, then check again:",
    "engineAuthCheck": "Check authentication",
    "engineAuthChecking": "Checking authentication…",
    "engineAuthCheckFailed": "Cannot check authentication. Check the device connection and try again.",
    "engineAgentUpgrade": "This Agent needs an update to support this action.",
    "refreshWaitHint": "Refresh starts after the current task and queued messages finish.",
    "refreshWaitTurn": "Waiting for the current turn to finish. Nothing is interrupted.",
    "refreshWaitPermission": "Waiting on the permission request above — answer it and the refresh continues.",
    "refreshSlow": "Taking longer than expected. Completion has not been confirmed; do not submit again.",
    "refreshStalled": "Refresh needs attention",
    "refreshStalledHint": "The CLI stopped, but restoration was not confirmed. Retry resumes this same session and keeps its history.",
    "refreshRetry": "Retry refresh",
    "refreshElapsed": "Elapsed",

    "dragSession": "Drag to reorder; arrow keys also move this session",
    "sessionMenu": "Session menu",
    "selected": "Selected",
    "speedHint": "Applies to newly started or restarted/resumed Codex sessions. Fast availability and usage depend on the model and account; Astra Fast uses 2.5× ChatGPT credits where available. API billing is separate.",

    "agents": "Agents",
    "agentsSubtitle": "Connected machines and agent defaults",
    "machines": "Machines",
    "noMachines": "No connected machines",
    "connectMachine": "Run LMC on a computer to connect it",
    "defaults": "Defaults",
    "clearOverrides": "Clear overrides",
    "clearDescription": "Return every agent to defaults",
    "permission": "Permission",
    "model": "Model",
    "effort": "Effort",
    "customModel": "Custom model…",
    "customCodex": "Custom Codex model",
    "modelId": "Enter an exact model ID",
    "modelHint": "Enter an exact model ID. Availability depends on your Codex account or API configuration.",
    "useDefault": "Use default",
    "defaultLabel": "Default",
    "none": "None",
    "contextHint": "Enter tokens; leave blank to use the backend default. Applies to newly started or restarted/resumed Codex sessions. Running sessions keep their existing configuration.",
    "windowHint": "For newly started or restarted sessions. Does not expand the model’s actual capacity.",
    "compactHint": "Codex may compact earlier according to its model limits.",
    "resetContext": "Use backend context defaults",
    "resetContextHint": "Clear both overrides for future starts and resumes",
    "positiveTokens": "Enter a positive whole number of tokens, or leave blank for the backend default.",
    "compactBelowWindow": "Auto-compaction threshold must be smaller than the context window.",
    "renameSession": "Rename session",
    "renameHint": "This name is synced with your account and will not be replaced by automatic CLI titles.",
    "namePlaceholder": "Session name",
    "invalidName": "Enter a name of 1–200 characters.",
    "resetName": "Restore automatic name",
    "archive": "Archive",
    "session": "Session",
    "clientLogs": "Client logs",
    "auto": "Auto",
    "workspace": "Workspace",
    "readOnly": "Read",
    "yolo": "Yolo",
    "edits": "Edits",
    "plan": "Plan",
    "customModelDescription": "custom model",
    "millionContext": "1M context",
    "invalidEffort": "Model and reasoning effort are incompatible. Message not sent. Choose a supported level: ",
    "project": "Project",
    "worktree": "Worktree",
    "searchMachine": "Search machines…",
    "searchWorkspace": "Search workspaces…",
    "searchWorktree": "Search worktrees…",
    "searchAgent": "Search agents…",
    "searchModel": "Search models…",
    "searchEffort": "Search efforts…",
    "searchPermission": "Search permissions…",
    "newWorktree": "New worktree",
    "noWorktree": "No worktree",
    "createNew": "Create new",
    "mainWorkspace": "Main"
};

export const localFeatureZhHans = {
    "quotaTitle": "账户额度",
    "quotaRefresh": "刷新额度",
    "quotaUnknown": "暂无数据",
    "quotaPending": "首次使用后起算",
    "quotaAwaitReset": "等待新窗口读数",
    "quotaFiveHour": "5 小时剩余",
    "quotaWeekly": "本周剩余",
    "quotaFable": "Fable 本周剩余",
    "quotaFableSpent": "Fable 本周已用完",
    "quotaFableCovered": "周额度可覆盖",
    "quotaFableConvention": "仪表盘口径：Fable 满池折算为 50 点周额度",
    "quotaWaiting": "等待设备上报额度",
    "quotaStale": "最近成功读数",
    "quotaOffline": "等待已配置额度来源的设备上线",
    "quotaRetryHint": "暂时无法更新，将自动重试。",
    "quotaShared": "同一账户跨设备共用 · 不累加",
    "quotaPaceMarker": ({ floor }: { floor: string }) => `按日均分，今日结束前不低于 ${floor}%`,
    "quotaReset": ({ date }: { date: string }) => `${date} 重置`,
    "quotaPaceDay": ({ day, days }: { day: number; days: number }) => `第 ${day}/${days} 天 · 按日均分`,
    "quotaOver": ({ points }: { points: string }) => `今日已超支 ${points} 点`,
    "quotaToday": ({ points }: { points: string }) => `今日还可用 ${points} 点`,
    "quotaFableShare": ({ points }: { points: string }) => `≈ ${points} 点周额度`,
    "quotaFableGap": ({ points }: { points: string }) => `缺 ${points} 点`,
    "quotaFableSyncPending": "待同步周期",
    "quotaCredits": ({ count }: { count: number }) => `额度重置券 ${count} 张`,
    "quotaExpires": ({ date }: { date: string }) => `最早 ${date} 到期`,
    "quotaSampled": ({ date }: { date: string }) => `${date} 采样`,

    "loginContinue": "继续登录",
    "loginViewRecovery": "查看恢复进度",
    "loginTitle": "重新登录",
    "loginHint": "在当前设备完成授权，让会话所在设备重新登录。草稿、历史和排队消息都会保留。",
    "loginRecheck": "我已登录，重新检查",
    "loginAutoCheck": "正在检查认证并尝试安全恢复…",
    "loginOpen": "打开官方授权页",
    "loginOfficialHint": "在官方页面完成登录；如果页面给出一次性授权码，回到这里粘贴。",
    "loginGoogleHint": "在官方页面选择「Continue with Google」，使用你原来的账号。",
    "loginDeviceHint": "在官方页面输入设备码。授权完成后，目标设备会自动检测。",
    "loginCopyLink": "复制授权链接",
    "loginCopied": "已复制",
    "loginHasCode": "已有授权码，继续",
    "loginCodeTitle": "粘贴授权码",
    "loginCodeHint": "填写官方页面的一次性授权码。仅加密发送到目标设备，不会保存到聊天记录。",
    "loginCodePlaceholder": "一次性授权码",
    "loginSubmit": "提交并验证",
    "loginBack": "返回授权页",
    "loginWaiting": "等待完成授权",
    "loginStarting": "正在目标设备启动登录…",
    "loginSubmitting": "正在提交授权码…",
    "loginVerifying": "正在检查目标设备的认证…",
    "loginRecovering": "已检测到登录 · 正在恢复会话",
    "loginComplete": "会话恢复结果",
    "loginRestored": "已恢复",
    "loginWaitTurn": "等待当前回合安全结束",
    "loginFailedSession": "恢复需要处理",
    "loginSafeHint": "忙碌会话会在当前回合和队列处理完后刷新。关闭面板不会打断恢复。",
    "loginNoResend": "不会自动重发任务。请先检查原回合的执行结果，再决定是否重新发送。",
    "loginKeepRunning": "可以关闭此面板，在另一台已登录 LMC 的设备上继续。",
    "loginLifetime": "LMC 本次登录剩余时间",
    "loginClose": "关闭",
    "loginReturn": "返回会话",
    "loginCancel": "取消本次登录",
    "loginRetry": "重新发起登录",
    "loginRetryRecovery": "重新检查并恢复",
    "loginQr": "用手机扫码完成授权",
    "loginDevice": "目标设备",
    "loginErrorRequired": "未检测到登录，请重新登录后继续。",
    "loginErrorUnknown": "暂时无法确认认证状态，不代表已退出登录。请检查连接后重试。",
    "loginErrorUnsupported": "此会话使用自定义认证配置，请在目标设备使用原有登录方式。",
    "loginErrorOffline": "目标设备或会话暂时不可用，连接恢复后请重新检查。",
    "loginErrorUpgrade": "请更新设备 Agent 和当前会话后使用远程登录，不会自动打断当前会话。",
    "loginErrorBusy": "已有登录或恢复正在进行，请继续当前流程。",
    "loginErrorInvalidCode": "授权码未被接受，请检查后重试，或重新发起登录。",
    "loginErrorLoginFailed": "官方登录未完成。请重新发起；使用设备授权时请确认账号已允许设备登录。",
    "loginErrorStale": "本次登录已不再有效，请重新检查是否有新的登录流程。",
    "loginErrorCancelled": "本次登录已取消，会话和消息已保留。",
    "loginErrorExpired": "LMC 本次登录已超时，请重新发起。",
    "modelParametersHint": "选择本会话的模型参数预设",

    "changeProjectAvatar": "更换头像",
    "workingState": "工作中",
    "attentionState": "待确认",
    "onlineState": "在线",
    "offlineState": "离线",

    "refreshConfiguration": "刷新会话配置",
    "legacySessionConfig": "这个运行中的会话尚未支持安全更新。请先停止并恢复一次，即可使用此功能；系统不会自动打断它。",
    "sessionConfigValidation": "请输入正整数 token 数；压缩阈值必须小于上下文窗口。",
    "configQueued": "已排队，等待会话空闲后应用。",
    "configFailed": "配置更新失败，未创建替代会话。请在连接正常后重试。",
    "configRefreshing": "正在为原会话加载更新后的 CLI…",
    "refreshWaiting": "等待刷新",
    "refreshRestarting": "正在重启 CLI、恢复原会话",
    "refreshVerifying": "正在检查配置与工具",
    "refreshComplete": "刷新完成",
    "engineAuthRequired": "需要登录认证",
    "engineAuthUnknown": "暂时无法确认认证状态",
    "engineAuthReady": "已检测到登录配置",
    "engineAuthHint": "请在本会话所在设备的终端执行下方命令，登录后重新检查：",
    "engineAuthCheck": "重新检查认证",
    "engineAuthChecking": "正在检查认证…",
    "engineAuthCheckFailed": "认证检查失败，请检查设备连接后重试。",
    "engineAgentUpgrade": "当前 Agent 版本不支持此操作，请更新后恢复会话。",
    "refreshWaitHint": "当前任务与排队消息结束后自动刷新。",
    "refreshWaitTurn": "等当前回合跑完，不会打断它。",
    "refreshWaitPermission": "在等上面那条权限请求——你回复了就继续。",
    "refreshSlow": "耗时较长，尚未确认完成，请勿重复提交。",
    "refreshStalled": "刷新需要处理",
    "refreshStalledHint": "CLI 已停止，但未确认恢复成功。重试会恢复当前会话，并保留历史记录。",
    "refreshRetry": "重试刷新",
    "refreshElapsed": "已等待",

    "dragSession": "拖动排序，也可用上下方向键移动会话",
    "sessionMenu": "会话菜单",
    "selected": "已选择",
    "speedHint": "对新建或重新启动／恢复的 Codex 会话生效。快速模式的可用性与额度消耗取决于模型和账号；Astra Fast 可用时消耗 2.5 倍 ChatGPT 额度，API 单独计费。",

    "agents": "智能体",
    "agentsSubtitle": "已连接的设备与智能体默认设置",
    "machines": "设备",
    "noMachines": "暂无已连接的设备",
    "connectMachine": "在电脑上运行 LMC 即可连接",
    "defaults": "默认设置",
    "clearOverrides": "清除自定义设置",
    "clearDescription": "恢复所有智能体的默认设置",
    "permission": "权限模式",
    "model": "模型",
    "effort": "推理强度",
    "customModel": "自定义模型…",
    "customCodex": "自定义 Codex 模型",
    "modelId": "输入完整模型 ID",
    "modelHint": "输入完整模型 ID。是否可用取决于 Codex 账号或 API 配置。",
    "useDefault": "使用默认设置",
    "defaultLabel": "默认",
    "none": "无",
    "contextHint": "输入 token 数，留空使用后端默认值。仅对新建或重新启动恢复的 Codex 会话生效，正在运行的会话保持原配置。",
    "windowHint": "对新建或重新启动的会话生效，不会扩大模型的实际容量。",
    "compactHint": "Codex 可能根据模型限制提前压缩。",
    "resetContext": "恢复后端上下文默认设置",
    "resetContextHint": "清除两项自定义值，下次启动或恢复时使用后端默认设置",
    "positiveTokens": "请输入正整数 token 数，或留空使用后端默认值。",
    "compactBelowWindow": "自动压缩阈值必须小于上下文窗口大小。",
    "renameSession": "重命名会话",
    "renameHint": "名称随账号同步，CLI 自动生成的标题不会覆盖它。",
    "namePlaceholder": "会话名称",
    "invalidName": "请输入 1～200 个字符的会话名称。",
    "resetName": "恢复自动命名",
    "archive": "归档",
    "session": "会话",
    "clientLogs": "客户端日志",
    "auto": "自动",
    "workspace": "工作区",
    "readOnly": "只读",
    "yolo": "完全放行",
    "edits": "允许编辑",
    "plan": "规划",
    "customModelDescription": "自定义模型",
    "millionContext": "1M 上下文",
    "invalidEffort": "模型与推理强度不兼容，消息未发送。请选择支持的强度：",
    "project": "项目",
    "worktree": "工作树",
    "searchMachine": "搜索设备…",
    "searchWorkspace": "搜索工作区…",
    "searchWorktree": "搜索工作树…",
    "searchAgent": "搜索智能体…",
    "searchModel": "搜索模型…",
    "searchEffort": "搜索推理强度…",
    "searchPermission": "搜索权限模式…",
    "newWorktree": "新建工作树",
    "noWorktree": "不使用工作树",
    "createNew": "新建",
    "mainWorkspace": "主工作区"
};

export const localFeatureZhHant = {
    "quotaTitle": "账户额度",
    "quotaRefresh": "刷新额度",
    "quotaUnknown": "暂无数据",
    "quotaPending": "首次使用后起算",
    "quotaAwaitReset": "等待新窗口读数",
    "quotaFiveHour": "5 小时剩余",
    "quotaWeekly": "本周剩余",
    "quotaFable": "Fable 本周剩余",
    "quotaFableSpent": "Fable 本周已用完",
    "quotaFableCovered": "周额度可覆盖",
    "quotaFableConvention": "仪表盘口径：Fable 满池折算为 50 点周额度",
    "quotaWaiting": "等待设备上报额度",
    "quotaStale": "最近成功读数",
    "quotaOffline": "等待已配置额度来源的设备上线",
    "quotaRetryHint": "暂时无法更新，将自动重试。",
    "quotaShared": "同一账户跨设备共用 · 不累加",
    "quotaPaceMarker": ({ floor }: { floor: string }) => `按日均分，今日结束前不低于 ${floor}%`,
    "quotaReset": ({ date }: { date: string }) => `${date} 重置`,
    "quotaPaceDay": ({ day, days }: { day: number; days: number }) => `第 ${day}/${days} 天 · 按日均分`,
    "quotaOver": ({ points }: { points: string }) => `今日已超支 ${points} 点`,
    "quotaToday": ({ points }: { points: string }) => `今日还可用 ${points} 点`,
    "quotaFableShare": ({ points }: { points: string }) => `≈ ${points} 点周额度`,
    "quotaFableGap": ({ points }: { points: string }) => `缺 ${points} 点`,
    "quotaFableSyncPending": "待同步周期",
    "quotaCredits": ({ count }: { count: number }) => `额度重置券 ${count} 张`,
    "quotaExpires": ({ date }: { date: string }) => `最早 ${date} 到期`,
    "quotaSampled": ({ date }: { date: string }) => `${date} 采样`,

    "loginContinue": "继续登录",
    "loginViewRecovery": "查看恢复进度",
    "loginTitle": "重新登录",
    "loginHint": "在当前设备完成授权，让会话所在设备重新登录。草稿、历史和排队消息都会保留。",
    "loginRecheck": "我已登录，重新检查",
    "loginAutoCheck": "正在检查认证并尝试安全恢复…",
    "loginOpen": "打开官方授权页",
    "loginOfficialHint": "在官方页面完成登录；如果页面给出一次性授权码，回到这里粘贴。",
    "loginGoogleHint": "在官方页面选择「Continue with Google」，使用你原来的账号。",
    "loginDeviceHint": "在官方页面输入设备码。授权完成后，目标设备会自动检测。",
    "loginCopyLink": "复制授权链接",
    "loginCopied": "已复制",
    "loginHasCode": "已有授权码，继续",
    "loginCodeTitle": "粘贴授权码",
    "loginCodeHint": "填写官方页面的一次性授权码。仅加密发送到目标设备，不会保存到聊天记录。",
    "loginCodePlaceholder": "一次性授权码",
    "loginSubmit": "提交并验证",
    "loginBack": "返回授权页",
    "loginWaiting": "等待完成授权",
    "loginStarting": "正在目标设备启动登录…",
    "loginSubmitting": "正在提交授权码…",
    "loginVerifying": "正在检查目标设备的认证…",
    "loginRecovering": "已检测到登录 · 正在恢复会话",
    "loginComplete": "会话恢复结果",
    "loginRestored": "已恢复",
    "loginWaitTurn": "等待当前回合安全结束",
    "loginFailedSession": "恢复需要处理",
    "loginSafeHint": "忙碌会话会在当前回合和队列处理完后刷新。关闭面板不会打断恢复。",
    "loginNoResend": "不会自动重发任务。请先检查原回合的执行结果，再决定是否重新发送。",
    "loginKeepRunning": "可以关闭此面板，在另一台已登录 LMC 的设备上继续。",
    "loginLifetime": "LMC 本次登录剩余时间",
    "loginClose": "关闭",
    "loginReturn": "返回会话",
    "loginCancel": "取消本次登录",
    "loginRetry": "重新发起登录",
    "loginRetryRecovery": "重新检查并恢复",
    "loginQr": "用手机扫码完成授权",
    "loginDevice": "目标设备",
    "loginErrorRequired": "未检测到登录，请重新登录后继续。",
    "loginErrorUnknown": "暂时无法确认认证状态，不代表已退出登录。请检查连接后重试。",
    "loginErrorUnsupported": "此会话使用自定义认证配置，请在目标设备使用原有登录方式。",
    "loginErrorOffline": "目标设备或会话暂时不可用，连接恢复后请重新检查。",
    "loginErrorUpgrade": "请更新设备 Agent 和当前会话后使用远程登录，不会自动打断当前会话。",
    "loginErrorBusy": "已有登录或恢复正在进行，请继续当前流程。",
    "loginErrorInvalidCode": "授权码未被接受，请检查后重试，或重新发起登录。",
    "loginErrorLoginFailed": "官方登录未完成。请重新发起；使用设备授权时请确认账号已允许设备登录。",
    "loginErrorStale": "本次登录已不再有效，请重新检查是否有新的登录流程。",
    "loginErrorCancelled": "本次登录已取消，会话和消息已保留。",
    "loginErrorExpired": "LMC 本次登录已超时，请重新发起。",
    "modelParametersHint": "選擇本工作階段的模型參數預設",

    "changeProjectAvatar": "更換頭像",
    "workingState": "工作中",
    "attentionState": "待確認",
    "onlineState": "線上",
    "offlineState": "離線",

    "refreshConfiguration": "重新載入工作階段設定",
    "legacySessionConfig": "這個執行中的工作階段尚未支援安全更新。請先停止並恢復一次，即可使用此功能；系統不會自動打斷它。",
    "sessionConfigValidation": "請輸入正整數 token 數；壓縮閾值必須小於上下文視窗。",
    "configQueued": "已排隊，等待工作階段閒置後套用。",
    "configFailed": "設定更新失敗，未建立替代工作階段。請在連線正常後重試。",
    "configRefreshing": "正在為原工作階段載入更新後的 CLI…",
    "refreshWaiting": "等待重新整理",
    "refreshRestarting": "正在重新啟動 CLI、恢復原工作階段",
    "refreshVerifying": "正在檢查設定與工具",
    "refreshComplete": "重新整理完成",
    "engineAuthRequired": "需要登入驗證",
    "engineAuthUnknown": "暫時無法確認驗證狀態",
    "engineAuthReady": "已偵測到登入設定",
    "engineAuthHint": "請在本對話所在裝置的終端執行下方命令，登入後重新檢查：",
    "engineAuthCheck": "重新檢查驗證",
    "engineAuthChecking": "正在檢查驗證…",
    "engineAuthCheckFailed": "驗證檢查失敗，請檢查裝置連線後重試。",
    "engineAgentUpgrade": "目前 Agent 版本不支援此操作，請更新後恢復對話。",
    "refreshWaitHint": "目前任務與排隊訊息結束後自動重新整理。",
    "refreshWaitTurn": "等目前回合跑完，不會打斷它。",
    "refreshWaitPermission": "在等上面那條權限請求——你回覆了就繼續。",
    "refreshSlow": "耗時較長，尚未確認完成，請勿重複提交。",
    "refreshStalled": "重新整理需要處理",
    "refreshStalledHint": "CLI 已停止，但尚未確認恢復成功。重試會恢復目前會話，並保留歷史記錄。",
    "refreshRetry": "重試重新整理",
    "refreshElapsed": "已等待",

    "dragSession": "拖動排序，也可用上下方向鍵移動工作階段",
    "sessionMenu": "工作階段選單",
    "selected": "已選擇",
    "speedHint": "對新建或重新啟動／恢復的 Codex 工作階段生效。快速模式的可用性與額度消耗取決於模型和帳號；Astra Fast 可用時消耗 2.5 倍 ChatGPT 額度，API 單獨計費。",

    "agents": "智慧代理",
    "agentsSubtitle": "已連線的裝置與智慧代理預設設定",
    "machines": "裝置",
    "noMachines": "暫無已連線的裝置",
    "connectMachine": "在電腦上執行 LMC 即可連線",
    "defaults": "預設設定",
    "clearOverrides": "清除自訂設定",
    "clearDescription": "還原所有智慧代理的預設設定",
    "permission": "權限模式",
    "model": "模型",
    "effort": "推理強度",
    "customModel": "自訂模型…",
    "customCodex": "自訂 Codex 模型",
    "modelId": "輸入完整模型 ID",
    "modelHint": "輸入完整模型 ID。是否可用取決於 Codex 帳號或 API 設定。",
    "useDefault": "使用預設設定",
    "defaultLabel": "預設",
    "none": "無",
    "contextHint": "輸入 token 數，留空使用後端預設值。僅對新建或重新啟動恢復的 Codex 對話生效，執行中的對話維持原設定。",
    "windowHint": "對新建或重新啟動的對話生效，不會擴大模型的實際容量。",
    "compactHint": "Codex 可能依模型限制提前壓縮。",
    "resetContext": "還原後端上下文預設設定",
    "resetContextHint": "清除兩項自訂值，下次啟動或恢復時使用後端預設設定",
    "positiveTokens": "請輸入正整數 token 數，或留空使用後端預設值。",
    "compactBelowWindow": "自動壓縮門檻必須小於上下文視窗大小。",
    "renameSession": "重新命名對話",
    "renameHint": "名稱隨帳號同步，CLI 自動產生的標題不會覆蓋它。",
    "namePlaceholder": "對話名稱",
    "invalidName": "請輸入 1～200 個字元的對話名稱。",
    "resetName": "還原自動命名",
    "archive": "封存",
    "session": "對話",
    "clientLogs": "用戶端記錄",
    "auto": "自動",
    "workspace": "工作區",
    "readOnly": "唯讀",
    "yolo": "完全放行",
    "edits": "允許編輯",
    "plan": "規劃",
    "customModelDescription": "自訂模型",
    "millionContext": "1M 上下文",
    "invalidEffort": "模型與推理強度不相容，訊息未傳送。請選擇支援的強度：",
    "project": "專案",
    "worktree": "工作樹",
    "searchMachine": "搜尋裝置…",
    "searchWorkspace": "搜尋工作區…",
    "searchWorktree": "搜尋工作樹…",
    "searchAgent": "搜尋智慧代理…",
    "searchModel": "搜尋模型…",
    "searchEffort": "搜尋推理強度…",
    "searchPermission": "搜尋權限模式…",
    "newWorktree": "新增工作樹",
    "noWorktree": "不使用工作樹",
    "createNew": "新增",
    "mainWorkspace": "主工作區"
};
