import { afterAll, expect, it } from 'vitest';
import { randomBytes, randomUUID } from 'node:crypto';
import { io, Socket } from 'socket.io-client';
import { db } from '@/storage/db';
import { lmcAuth } from './auth';
const origin=process.env.LMC_PUBLIC_ORIGIN!;
const ids:string[]=[],sockets:Socket[]=[];
afterAll(async()=>{for(const s of sockets)s.close();for(const accountId of ids){await db.sessionMessage.deleteMany({where:{session:{accountId}}});await db.session.deleteMany({where:{accountId}});await db.machine.deleteMany({where:{accountId}});await db.project.deleteMany({where:{accountId}});await db.lmcLogin.deleteMany({where:{accountId}});await db.account.delete({where:{id:accountId}});}await db.$disconnect();});
it.skipIf(process.env.LMC_LIVE_TESTS!=='1')('preserves real HTTP messages, account isolation and Socket RPC',async()=>{
 const id=await lmcAuth.createAccount('test-'+randomBytes(8).toString('hex'),randomBytes(24).toString('hex'));ids.push(id);
 const token=await lmcAuth.createToken(id,undefined,'web');
 const request=async(path:string,body?:unknown,auth=token)=>{const response=await fetch(origin+path,{method:body?'POST':'GET',headers:{authorization:'Bearer '+auth,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,body:await response.json() as any};};
 const created=await request('/v1/sessions',{tag:randomUUID(),metadata:'encrypted-metadata',agentState:'encrypted-state'});expect(created.status).toBe(200);
 const sid=created.body.session.id;
 const project=await request('/v1/projects',{externalId:randomUUID(),metadata:'encrypted-project'});expect(project.status).toBe(200);
 const machine=await request('/v1/machines',{id:randomUUID(),metadata:'encrypted-machine'});expect(machine.status).toBe(200);
 const payload={messages:[{localId:'one',content:'first-encrypted'},{localId:'two',content:'second-encrypted'}]};
 const first=await request('/v3/sessions/'+sid+'/messages',payload);expect(first.status).toBe(200);
 const retry=await request('/v3/sessions/'+sid+'/messages',payload);expect(retry.status).toBe(200);expect(retry.body.messages.map((x:any)=>x.id)).toEqual(first.body.messages.map((x:any)=>x.id));
 const history=await request('/v3/sessions/'+sid+'/messages?before_seq=2147483647&limit=20');expect(history.status).toBe(200);expect(history.body.messages).toHaveLength(2);
 expect((await request('/v1/sessions',undefined,'invalid')).status).toBe(401);
 const other=await lmcAuth.createAccount('test-'+randomBytes(8).toString('hex'),randomBytes(24).toString('hex'));ids.push(other);
 expect((await request('/v3/sessions/'+sid+'/messages?before_seq=2147483647&limit=20',undefined,await lmcAuth.createToken(other))).status).toBe(404);
 const connect=async(auth:Record<string,string>)=>{const socket=io(origin,{path:'/v1/updates',transports:['websocket'],auth,reconnection:false});sockets.push(socket);await new Promise<void>((resolve,reject)=>{socket.once('connect',resolve);socket.once('connect_error',reject);});return socket;};
 const device=await connect({token,clientType:'session-scoped',sessionId:sid}),web=await connect({token,clientType:'user-scoped'});
 device.on('rpc-request',(_data,ack)=>ack('encrypted-response'));
 const registered=new Promise<void>(resolve=>device.once('rpc-registered',()=>resolve()));device.emit('rpc-register',{method:sid+':lmc-check'});await registered;
 const result=await web.timeout(3000).emitWithAck('rpc-call',{method:sid+':lmc-check',params:'encrypted-request'});expect(result).toMatchObject({ok:true,result:'encrypted-response'});
},15_000);
